### ISSUE TITLE
Jetpack 5 L4T 34.1.1 , Jetson Orin , emotion_impl Make fails with error: invalid new-expression of abstract class type ‘EmotionAlgorithm’

### ISSUE THREAD

**Issue by eenav-iva** [katjasrz/deepstream_tao_interactive#1]
Jetpack 5 , Jetson Orin AGX , emotion_impl Make fails with error: invalid new-expression of abstract class type ‘EmotionAlgorithm’

desktop:~/deepstream_tao_interactive/deepstream-emotion-app/emotion_impl$ make
-fPIC -DDS_VERSION="6.0.0" -I /usr/local/cuda/include -I /opt/nvidia/deepstream/deepstream/sources/includes -I../includes -I /opt/nvidia/deepstream/deepstream/sources/includes/cvcore_headers -I /opt/nvidia/deepstream/deepstream/sources/gst-plugins/gst-nvdsvideotemplate/includes -I ../../deepstream-faciallandmark-app -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include
g++ -c -o emotion_impl.o -fPIC -DDS_VERSION=\"6.0.0\" -I /usr/local/cuda/include -I /opt/nvidia/deepstream/deepstream/sources/includes -I../includes -I /opt/nvidia/deepstream/deepstream/sources/includes/cvcore_headers -I /opt/nvidia/deepstream/deepstream/sources/gst-plugins/gst-nvdsvideotemplate/includes -I ../../deepstream-faciallandmark-app -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include emotion_impl.cpp
emotion_impl.cpp: In function ‘IDSCustomLibrary* CreateCustomAlgoCtx(DSCustom_CreateParams*)’:
emotion_impl.cpp:198:31: error: invalid new-expression of abstract class type ‘EmotionAlgorithm’
  198 |   return new EmotionAlgorithm();
      |                               ^
emotion_impl.cpp:132:7: note:   because the following virtual functions are pure within ‘EmotionAlgorithm’:
  132 | class EmotionAlgorithm : public DSCustomLibraryBase
      |       ^~~~~~~~~~~~~~~~
In file included from emotion_impl.cpp:43:
/opt/nvidia/deepstream/deepstream/sources/gst-plugins/gst-nvdsvideotemplate/includes/nvdscustomlib_base.hpp:56:19: note: 	‘virtual char* DSCustomLibraryBase::QueryProperties()’
   56 |     virtual char* QueryProperties () = 0;
      |                   ^~~~~~~~~~~~~~~
make: *** [Makefile:64: emotion_impl.o] Error 1

**Comment by katjasrz** [comment]
Yes, the Emotion App hasn't been updated for the JetPack 5, and I'm aware of this error. Planning to address this in two weeks

**Comment by katjasrz** [comment]
Sorry, that it took longer, but I've finally found time to fix it for the newest SW version. Now both demos work also on JP 5.0 and with the newest Deepstream
